runtime: nodejs12

instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

network:
  forwarded_ports:
    - 443
